config/routes.rb
Rails.application.routes.draw do
  root 'attendance_page#top'
  
  get '/signup', to:'users#new'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  
  
  resources :bases, only:[:new, :index, :create, :edit, :update, :destroy]

 
 resources :users do
  member do
   get 'edit_basic_info'
   patch 'update_basic_info'
   get 'form_edit'
   get 'info_correction'
   get 'attendances/edit_one_month'
   patch 'attendances/update_one_month'
   #勤怠を確認する
   get 'show_confirmation'
   #１ヶ月の勤怠申請
   patch 'attendances/update_one_month_request'
   get 'worker'
   
  end 
  collection {post :import}
  
  resources :attendances, only: :update do
    member do
      
      #残業申請
      get 'edit_overtime_request'
      patch 'update_overtime_request'
      
      #残業申請承認
      get 'edit_overtime_approval'
      patch 'update_overtime_approval'
      
      #勤怠承認
      get 'edit_attendance_change_approval'
      patch 'update_attendance_change_approval'  
      
      #1ヶ月の勤怠承認
      get 'edit_one_month_approval'
      patch 'update_one_month_approval'
      
      get 'attendance_log'
    end 
  end
 end
end
  

app/models/user.rb
class User < ApplicationRecord
 has_many :attendances, dependent: :destroy
 # has_many :applies, dependent: :destroy
 
  validates :name, presence: true
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true
  
  validates :department, length: { in: 2..30 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
 
  
  
 has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil:true
  
 def User.digest(string) #デフォルトで使用
   cost =
    if ActiveModel::SecurePassword.min_cost
      BCrypt::Engine::MIN_COST
    else
      BCrypt::Engine.cost
    end
   BCrypt::Password.create(string,cost: cost)
 end
 
 def User.new_token
   SecureRandom.urlsafe_base64
 end
 
 def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
 end

 def authenticated?(remember_token)
   return false if remember_digest.nil?
   BCrypt::Password.new(remember_digest).is_password?(remember_token)
 end
 
 def forget
   update_attribute(:remember_digest, nil)
 end
 
 #csv出力のメソッド
 def self.import(file)
  CSV.foreach(file.path, headers: true) do |row|
   user = find_by(id: row["id"]) || new
   user.attributes = row.to_hash.slice(*updatable_attributes)
   user.save!(validate: false)
  end
 end

 def self.updatable_attributes
  ["name", "email","department","employee_number","uid","basic_time","designated_work_start_time","designated_work_end_time","superior","admin","password"]
 end 
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show,:edit,:update,:destroy,:edit_basic_info,:update_basic_info,:show_confirmation,:form_edit,:info_correction_user_path]
  before_action :logged_in_user, only: [:index,:edit,:update,:destroy,:edit_basic_info,:update_basic_info] #管理者のみに変更する(admin)
  before_action :correct_user, only: [:show,:edit,:update] 
  before_action :admin_user, only: [:index,:worker,:destroy,:edit_basic_info,:update_basic_info,:form_edit,:info_correction]
  before_action :set_one_month, only: [:show,:show_confirmation]
  before_action :select_superiors, only: [:show]
  before_action :admin_ban, only: [:show, :form_edit]
  
   def show
     @worked_sum = @attendances.where.not(started_at:nil).count
     @superiors = User.where(superior: true).where.not(id: @user.id)
     @one_month_approval_sum = Attendance.where(one_month_request_boss: @user.name, one_month_request_status: "申請中").count
     @attendances_sum = Attendance.where(attendances_request_superiors: @user.name, attendance_approval_status: "申請中").count
     @attendance_overtime_sum = Attendance.where(overtime_request_superior: @user.name, request_overtime_status: "申請中").count
     respond_to do |format|
       format.html
       format.csv do |csv|
         send_attendances_csv(@attendances)
       end
     end   
   end
  
   def new
     @user = User.new
   end
  
   def create
     @user = User.new(user_params)
     if @user.save
       log_in @user
       flash[:success] = "新規作成に成功しました。"
       redirect_to @user
     else
       flash.now[:danger] = "ユーザー登録に失敗しました"
       render :new
     end
   end

 def index
   @users = User.paginate(page: params[:page]).order(:id)
 end
 
  def edit
      
  end
  
  def update
      if @user.update_attributes(user_params)
        flash[:success] = "ユーザー情報を更新しました。"
        redirect_to @user
      else
        render :edit
      end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}を削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
    if @user.update_attributes(basic_info_params)
     flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger]= "#{@user.name}の更新は失敗しました" + @user.errors.full_messages.join("、")
    end
    redirect_to users_url
  end
  
  def worker
   Attendance.where.not(started_at: nil).each do |attendance|
       if (Date.current == attendance.worked_on) && attendance.finished_at.nil?
           @worker_users = User.all.includes(:attendances)
       end
   end
  end
  
  def show_confirmation
   @worked_sum = @attendances.where.not(started_at:nil).count
   @superiors = User.where(superior: true).where.not(id: @user.id)
   @one_month_approval_sum = Attendance.where(one_month_request_boss: @user.name, one_month_request_status: "申請中").count
  end
  
  def import
    if params[:file].blank?
        flash[:danger] = "csvファイルが選択されていません"
        redirect_to users_url
    else
      if User.import(params[:file])
          flash[:success] = "CSVファイルのインポートに成功しました"
      else
          flash[:danger] = "CSVファイルのインポートに失敗しました"
      end
      redirect_to users_url
    end
  end
  
  def form_edit
  end
  
  def info_correction
  end

 private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,:department,:designated_work_start_time, :designated_work_end_time)
    end

    
    
    def basic_info_params
      params.require(:user).permit(:name, :email, :department, :employee_number, 
                                   :uid, :designated_work_start_time, :designated_work_end_time,
                                   :password, :password_confirmation)
    end
    
    def workers_member
       @user.attendances.where(started_at:present, finished_at:blank)
    end
    
    def send_attendances_csv(attendances)
        bom = "\uFEFF"
        
        csv_data = CSV.generate do |csv|
          header = %w(日付 出勤時間 退勤時間)
          csv << header
          
          attendances. each do |day|
              column_values = [
                  day.worked_on.strftime("%Y年%m月%d日(#{$days_of_the_week[day.worked_on.wday]})"),
                  if day.started_at.present? 
                      l(day.started_at, format: :time)
                  else
                      nil
                  end,
                  if day.finished_at.present? 
                      l(day.finished_at, format: :time)
                  else
                      nil
                  end
              ]
              csv << column_values
          end
        end
        send_data(csv_data, filename: "勤怠一覧.csv")
    end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  def format_basic_info(time)
    format("%.2f",((time.hour*60)+ time.min)/60.0)
  end
  
   
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_edit_one_month_approval.html.erb
<% provide(:btn_text, '変更を返信する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          <%= form_with(model: @user, url: update_one_month_approval_user_attendance_path(@user), local: true, method: :patch) do |f| %>
            <% @attendances.each do |id, attendances| %>
              <% user = User.find(id)%>
              <h1 class="modal-title"><%= "【#{user.name}からの1ヶ月分勤怠申請】" %></h1>
               <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                <thead>
                  <tr>
                        <th>月</th>
                        <th>指示者確認㊞</th>
                        <th>変更</th>
                        <th>勤怠を確認する</th>
                  </tr>
                </thead>
                <tbody>
                  <% attendances.each do |day| %>              
                    <%= f.fields_for "attendances[]", day do |attendance| %>  
                      <tr>
                        <td><%= day.worked_on.month %>月</td>
                        <td><%= attendance.select :one_month_approval_status, ['なし', '申請中', '承認', '否認'] %></td>
                        <td><%= attendance.check_box :one_month_approval_check %></td>
                        <td><%= link_to "確認", show_confirmation_user_path(user), class: "btn btn-primary" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
              <div class="center">
                <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user,url: update_basic_info_user_path(@user), local: true, ) do |f| %>
  <%= render 'shared/error_messages', object: @user%>
  
  <%= f.label :name, class: "label-#{yield(:class_text)} label-title"%>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)} label-title"%>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :department, class: "label-#{yield(:class_text)} label-title"%>
  <%= f.text_field :department, class: "form-control" %>
  
  <%= f.label :employee_number, class: "label-#{yield(:class_text)} label-title"%>
  <%= f.text_field :employee_number, class: "form-control"%>
  
  <%= f.label :uid, class: "label-#{yield(:class_text)} label-title"%>
  <%= f.number_field :uid, class: "form-control"%>
  
  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)} label-title"%>
  <%= f.time_field :designated_work_start_time, class: "form-control"%>
  
  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)} label-title"%>
  <%= f.time_field :designated_work_end_time, class: "form-control"%>
  
  <%= f.label :password, class: "label-#{yield(:class_text)} label-title"%>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)} label-title"%>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  
  <%= f.submit "編集する", class: "btn btn-primary btn-block btn-edit" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, "user--edit")%>
<% provide(:button_text, "情報更新")%>


<h1>ユーザー情報の更新</h1>
  <div class = "row">
    <div class = "col-md-6 col-md-offset-3 ">
      <%= render 'form'%>
    </div>
  </div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info')%>");
$("#edit-basic-info").modal("show");

app/views/users/edit_one_month_approval.js.erb
$("#edit-one-month-approval").html("<%= escape_javascript(render 'edit_one_month_approval') %>");
$("#edit-one-month-approval").modal("show");

app/views/users/info_correction.html.erb
<h1>基本情報の修正</h1>
<div class  = "row">
    <div class = "col-md-6 col-md-offset-3">
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class = "user_show_container">
  <table class = "table table-bordered table-condensed table-hover user-table">
    <thead>
        <tr>  
          <th><%= link_to "⬅️️", user_path(date: @first_day.prev_month), class: "btn btn-info" %>
          <%= l(@first_day, format: :middle)%>　時間管理表
           <%= link_to "➡️",user_path(date: @first_day.next_month), class: "btn btn-info"%>
          </th>
          <th>
          <h5>指定勤務開始時間　　<%= l(@user.designated_work_start_time, format: :time)%></h5>
          <h5><p>指定勤務終了時間　　<%= l(@user.designated_work_end_time, format: :time) %></p></h5>
          </th>
          <th colspan= "3">基本時間　　<%=l(@user.basic_time, format: :time)%></th>
          <th>初日<%= l(@first_day, format: :short)%></th>
        </tr>
    </thead>
    <tbody>
        <tr>
          <td>所属：<%= @user.department.present? ? @user.department: "未所属" %></td>
          <td>氏名：<%= @user.name %></td>
          <td>コード</td>
          <td><%= @user.uid%></td>
          <td>出勤日数<%= @worked_on%></td>
          <td>締日<%= l(@last_day, format: :short)%></td>
        </tr>
    </tbody>
  </table>
</div>

<div>
  <% if @user.superior && current_user == @user %>
   <% if  @one_month_approval_sum > 0 %>
    <%= link_to "[ 所属長承認申請のお知らせ ]", edit_one_month_approval_user_attendance_path(@user), remote: true, class: "notice-color" %>
    <span style="border: solid 3px red;"><%= link_to "#{@one_month_approval_sum}件の通知があります", edit_one_month_approval_user_attendance_path(@user), remote: true, class: "notice-color" %></span><br>
   <% else %>
    <%= "[ 所属長承認申請のお知らせ ]" %><br>
   <% end %>
   <% if @attendances_sum > 0 %>
     <%=link_to "[  勤怠変更申請のお知らせ ]",edit_attendance_change_approval_user_attendance_path(@user), remote: true, class: "notice-color" %>
     <span style="border: solid 3px red;"><%= link_to "#{@attendances_sum}件の通知があります",edit_attendance_change_approval_user_attendance_path(@user), remote: true, class: "notice-color"%></span><br>
   <% else %>
     <%= "[勤怠変更申請のお知らせ]"%><br>
   <% end %>
   <% if @attendance_overtime_sum > 0%>
     <%=link_to "[ 残業申請のお知らせ]",edit_overtime_approval_user_attendance_path(@user), remote: true, class: "notice-color"%>
     <span style="border: solid 3px red;"><%= link_to "#{@attendance_overtime_sum}件の通知があります",edit_overtime_approval_user_attendance_path(@user), remote: true, class: "notice-color" %><br>
   <% else %>
     <%= "[残業申請のお知らせ]"%>
   <% end %>
  <% end %>
</div>



<!----- ボタン箇所--->
 <div class = "btn-user-show">
   <%= link_to "勤怠編集",attendances_edit_one_month_user_path(date:@first_day), class: "btn btn-primary"%>
   <%= link_to "CSV出力", user_path(format: :csv), class: "btn btn-primary"%>
   <p><%= link_to "勤怠修正ログ",attendance_log_user_attendance_path(@user.attendances), class: "btn btn-primary btn-md"%></p>
  </div>


<div class = "show_body">
  <table class = "table table-bordered table-condensed table-hover" id= "table-attendaces">
    <thead>
      <tr>
        <th rowspan = "3">残業指示</th>
        <th rowspan = "3">日付</th>
        <th rowspan = "3">曜日</th>
        <th colspan = "6">実績</th>
        <th colspan = "7" >所定外勤務</th>
      </tr>
      <tr>
        <td colspan = "4">出社</td>
        <td colspan = "2">退社</td>
        <td rowspan ="2">在社時間</td>
        <td rowspan = "2">備考</td>
        <td colspan = 2>終了予定時間</td>
        <td rowspan = "2">時間外時間</td>
        <td rowspan = "2">業務処理内容</td>
        <td rowspan = "2">指示者確認印</td>
      </tr>
      <tr>
        <td>時</td>
        <td>分</td>
        <td colspan ="2">勤怠ボタン</td>
        <td>時</td>
        <td>分</td>
        <td>時</td>
        <td>分</td>
      </tr>
    </thead>
        <tbody>
          <% @attendances.each do |day| %>
            <% user = day.user%>
          <tr>
            <td><%= link_to '残業申請', edit_overtime_request_user_attendance_path(@user,day), remote: true, class: "btn btn-primary"%></td>
            <td><%= l(day.worked_on,format: :short) %></td>
            <td><%= $days_of_the_week[day.worked_on.wday] %></td>
            <td><%= l(day.started_at, format: :hour) if day.started_at.present?%></td>
            <td><%= l(day.started_at, format: :minute) if day.started_at.present?%></td>
            <td colspan = "2">
               <% if btn_text = attendance_state(day) %>
                 <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
               <% end %>
            </td>
            <td><%= l(day.finished_at, format: :hour) if day.finished_at.present?%></td>
            <td><%= l(day.finished_at, format: :minute) if day.finished_at.present?%></td>
            <td>
              <%= str_times = working_times(day.after_finished_at, day.after_started_at, day.change) if day.after_finished_at.present? && day.after_started_at.present?%>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            </td>
            <td><%= day.note%></td>
            <td><%= l(day.change_end_time, format: :hour) if day.change_end_time.present?%></td>
            <td><%= l(day.change_end_time, format: :minute) if day.change_end_time.present?%></td>
            <td><%= overtime_culculation(day.change_end_time, user.designated_work_end_time, day.overtime_next_day) if day.change_end_time.present?%></td>
            <td><%= day.reason_for_application %></td>
            <td>
              <% if day.request_overtime_status == "申請中" %>
                <%= "#{day.overtime_request_superior}へ残業#{day.request_overtime_status}"%>
              <% elsif day.request_overtime_status =="承認" || day.request_overtime_status == "否認" %>
                <%= "#{day.overtime_request_superior}より残業#{day.request_overtime_status}"%>
              <% end %>
              <% if day.attendance_approval_status == "申請中"%><br>
                <%= "#{day.attendances_request_superiors}へ勤怠変更#{day.attendance_approval_status}"%><br>
              <% elsif day.attendance_approval_status == "承認" || day.attendance_approval_status == "否認"%><br>
                <%= "#{day.attendances_request_superiors}より勤怠変更#{day.attendance_approval_status}"%><br>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
        <tfoot>
         <tr>
          <td></td>
          <td>日数</td>
          <td colspan ="7">総合勤務時間</td>
          <td>累計在社時間</td>
          <td rowspan = "3"></td>
          <td rowspan = "3"></td>
          <td rowspan = "3"></td>
          <td rowspan = "3"></td>
           <td rowspan = "3"></td>
          <td rowspan = "3">
           <div class = "application-form">
            <% if current_user %>
              <% day = @user.attendances.find_by(worked_on: @first_day)%>
              <% if day %>
                <%= form_with(model: @user, url: attendances_update_one_month_request_user_path(@user), local: true, method: :patch) do |f| %>
                  <%= f.fields_for "attendances[]", day do |attendance|%>
                    <%= "所属長承認: "%>
                      <% if day.one_month_approval_status.nil? && day.one_month_request_status.nil?%>
                        <%= "末" %><br>
                      <% elsif day.one_month_request_status == "申請中"%>
                        <%= "#{day.one_month_request_boss}へ#{day.one_month_request_status}" %><br>
                      <% elsif (day.one_month_approval_status =="承認") || (day.one_month_approval_status =="否認") %>
                        <%="#{day.one_month_request_boss}から#{day.one_month_approval_status}済" %><br>
                      <% end %>
                    <%= attendance.collection_select :one_month_request_boss, @superiors, :name, :name, { include_blank: true }, required: true %>  
                  <% end %>
                    <br><%= f.submit "申請", class: "btn btn-primary" %></br>
                <% end %>
              <% end %>
            <% end %>
            </div>
           </td>
         </tr>
           <td></td>
           <td><%= @attendances.count%></td>
           <td colspan = "7"><%=format_basic_info(@user.work_time).to_f* @worked_sum%></td>
           <td><%= format("%.2f", @total_working_times.to_f) %></td>
         <tr>
         </tr>
    </tfoot>
  </table> 
</div>
　　<div id="edit-overtime-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
　　<div id="edit-overtime-approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
    <div id="receve_application_content" class=" modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
    <div id="edit-attendance-change-approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
    <div id="edit-one-month-approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
    
    <!--<div id="receive-change-attendance" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>-->
    <!--<div id="receive-one-month-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>-->
    
    
    
    


 

app/views/users/show_confirmation.html.erb
<% provide(:title, @user.name) %>

<div class = "user_show_container">
  <table class = "table table-bordered table-condensed table-hover user-table">
    <thead>
        <tr>  
          <th><%= l(@first_day, format: :middle)%> 時間管理表</th>
          <th>基本勤務時間　　<%= l(@user.work_time, format: :time)%></th>
          <th colspan= "3">基本時間　　<%=l(@user.basic_time, format: :time)%></th>
          <th>初日<%= l(@first_day, format: :short)%></th>
        </tr>
    </thead>
    <tbody>
        <tr>
          <td>所属：<%= @user.department.present? ? @user.department: "未所属" %></td>
          <td>氏名：<%= @user.name %></td>
          <td>コード</td>
          <td><%= @user.uid%></td>
          <td>出勤日数<%= @worked_on%></td>
          <td>締日<%= l(@last_day, format: :short)%></td>
        </tr>
    </tbody>
  </table>
</div>

<div>
  <!--<% if @user.superior && current_user == @user %>-->
  
  <!--  <%= link_to "[ 所属長承認申請のお知らせ ]", edit_one_month_approval_user_attendance_path(@user), remote: true, class: "notice-color" %>-->
  <!--  <span style="border: solid 3px red;"><%= link_to "#{@one_month_approval_sum}件の通知があります", edit_one_month_approval_user_attendance_path(@user), remote: true, class: "notice-color" %></span>-->
  
  <!--<% end %> -->
   
</div>


<!----- ボタン箇所--->
 <!--<div class = "btn-user-show">-->
 <!--  <%= link_to "勤怠編集", attendances_edit_one_month_user_path(@user), class: "btn btn-primary"%>-->
 <!--  <%= link_to "CSV出力", "#", class: "btn btn-primary"%>-->
 <!--  <p><%= link_to "勤怠修正ログ","#", class: "btn btn-primary btn-md"%></p>-->
 <!-- </div>-->


<div class = "show_body">
  <table class = "table table-bordered table-condensed table-hover" id= "table-attendaces">
    <thead>
      <tr>
        <th rowspan = "3">残業申請</th>
        <th rowspan = "3">日付</th>
        <th rowspan = "3">曜日</th>
        <th rowspan = "3">出勤退勤登録</th>
        <th colspan = "6">実績</th>
        <th colspan = "5" >所定外勤務</th>
      </tr>
      <tr>
        <td colspan = "2">出社</td>
        <td colspan = "2">退社</td>
        <td rowspan = "2">在社時間</td>
        <td rowspan = "2">備考</td>
        <td colspan = "2">終了予定時間</td>
        <td rowspan = "2">時間外時間</td>
        <td rowspan = "2">業務処理内容</td>
        <td rowspan = "2" >指示者確認印</td>
      </tr>
      <tr>
        <td>時</td>
        <td>分</td>
        <td>時</td>
        <td>分</td>
        <td>時</td>
        <td>分</td>
      </tr>
    </thead>
        <tbody>
          <% @attendances.each do |day| %>
          <tr>
            <td></td>
            <td><%= l(day.worked_on,format: :short) %></td>
            <td><%= $days_of_the_week[day.worked_on.wday] %></td>
             <td></td>
            <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
            <td><%= l(day.started_at.floor_to(15.minutes),format: :minute) if day.started_at.present? %></td>
            <td><%= l(day.finished_at,format: :hour) if day.finished_at.present? %></td>
            <td><%= l(day.finished_at.floor_to(15.minutes),format: :minute) if day.finished_at.present? %></td>
            <td>
              <% if day.started_at.present? && day.finished_at.present?%>
                <%= str_time = working_times(day.started_at, day.finished_at,day.change) %>
              <% end %>
            </td>
            <td><%= day.note %></td>
            <td><%=l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
            <td><%=l(day.finished_at, format: :minute) if day.finished_at.present?%></td>
            <td>
              
            </td>
            <td><%= day.reason_for_application%></td>
            <td>
               <% if day.request_overtime_status == "申請中"%>
                 <%="#{day.overtime_request_superior}へ残業#{day.request_overtime_status}" %><br>
               <% elsif (day.request_overtime_status == "承認") || (day.request_overtime_status =="否認") %>
                <%= "#{day.overtime_request_superior}より残業#{day.request_overtime_status}"%><br>
               <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
       
        <tfoot>
         <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td colspan = "6"></td>
          <td></td>
          <td></td>
          <td>
           <div class = "application-form">
          
            </div>
           </td>
    </tfoot>
  </table> 
</div>