config/routes.rb
Rails.application.routes.draw do
  root 'attendance_page#top'
  
  get '/signup', to:'users#new'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  
  
  resources :bases, only:[:new, :index, :create, :edit, :update, :destroy]

 
 resources :users do
  member do
   get 'edit_basic_info'
   patch 'update_basic_info'
   get 'form_edit'
   get 'info_correction'
   get 'attendances/edit_one_month'
   patch 'attendances/update_one_month'
   #勤怠を確認する
   get 'show_confirmation'
   #１ヶ月の勤怠申請
   patch 'attendances/update_one_month_request'
   get 'worker'
   
  end 
  collection {post :import}
  
  resources :attendances, only: :update do
    member do
      
      #残業申請
      get 'edit_overtime_request'
      patch 'update_overtime_request'
      
      #残業申請承認
      get 'edit_overtime_approval'
      patch 'update_overtime_approval'
      
      #勤怠承認
      get 'edit_attendance_change_approval'
      patch 'update_attendance_change_approval'  
      
      #1ヶ月の勤怠承認
      get 'edit_one_month_approval'
      patch 'update_one_month_approval'
      
      get 'attendance_log'
    end 
  end
 end
end
  

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  
  validates :worked_on, presence: true
  validates :note,length: { maximum: 50}

  validate :started_at_need_finished_at
  validate :started_at_fast_than_finished_at

  def started_at_need_finished_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  def started_at_fast_than_finished_at
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
  
 
 
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :receive_change_attendance,:edit_attendance_change_approval,:attendance_log]
  before_action :set_user_ids, only: [:edit_attendance_change_approval,:update_attendance_change_approval,:edit_overtime_request,:update_overtime_request,:edit_overtime_approval,:update_overtime_approval, :edit_one_month_approval, :update_one_month_approval]
  before_action :logged_in_user,only: [:update, :edit_one_month]
  before_action :set_one_month, only: [:edit_one_month,:edit_overtime_request]
  before_action :select_superiors, only: [:edit_one_month, :update_change_attendance]
  before_action :set_attendance ,only: [:edit_overtime_request,:update_overtime_request]
  
  
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  INVALID_ERROR_MSG = "無効なデータがあったので、更新をキャンセルしました。"
  NO_CHECK_ERROR_MSG = "変更にチェックがないものは更新できません。"
  
  def new
    @attendances = attendance.new
  end
  
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec:0))
        
        flash[:info] = "おはようございます"
      else
        flash[:danger] =  UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec:0))
        flash[:info] = "お疲れ様でした。"
      else
        flas[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  #残業申請（edit)モーダル
  def edit_overtime_request
    @superiors = User.where(superior: true).where.not(id: @user.id)
  end
  
  #残業申請モーダルの更新
  def update_overtime_request
    if overtime_request_params[:change_end_time].blank? || overtime_request_params[:reason_for_application].blank? || overtime_request_params[:overtime_request_superior].blank?
      flash[:danger] = "終了予定時間、残業理由、または指示者確認印がありません"   
    else
      if overtime_request_params[:change_end_time].present? && overtime_request_params[:reason_for_application].present? && overtime_request_params[:overtime_request_superior].present?
        params[:attendance][:request_overtime_status] = "申請中"
        @attendance.update(overtime_request_params)
        flash[:success] = "残業申請しました"
      else
        flash[:danger] = "残業申請が正しくありません"
      end
    end
    redirect_to @user
  end
  
  def edit_overtime_approval
    @attendances = Attendance.where(overtime_request_superior: @user.name, request_overtime_status: "申請中").order(:worked_on).group_by(&:user_id)
  end
  
  def update_overtime_approval
    overtime_approval_params.each do |id,item|
      attendance = Attendance.find(id)
      if item[:overtime_check]=="1"
        if item[:request_overtime_status]=="なし"
          attendance.change_end_time = nil
          attendance.overtime_next_day = nil
          attendance.reason_for_application = nil
          attendance.overtime_request_superior = nil
        end
        attendance.update(item)
         flash[:success] = "残業申請を承認しました"
      else
         flash[:danger] = "残業申請の承認に失敗しました"
      end
    end
    redirect_to @user
  end
  
  
  def edit_one_month
    @superiors = User.where(superior: true).where.not(id: @user.id)
  end
   
  
  
#社員による勤怠情報の修正
   def update_one_month
     a_count = 0
     ActiveRecord::Base.transaction do
        attendances_params.each do |id, item|
         if item[:attendances_request_superiors].present?
           if item[:after_started_at].blank? && item[:after_finished_at].present?
             flash[:danger]="出勤時間が必要です"
             redirect_to attendances_edit_one_month_user_url(date:params[:date])
           return
           elsif item[:after_started_at].present? && item[:after_finished_at].blank?
             flash[:danger] = "退勤時間が必要です"
             redirect_to attendances_edit_one_month_user_url(date:params[:date])
           return
           
           end
           attendance = Attendance.find(id)
           attendance.attendance_approval_status = "申請中"
           a_count += 1
           attendance.update!(item)
         end
        end
         
        if a_count > 0
          flash[:success] = "勤怠編集を#{a_count}件、申請しました。"
          redirect_to user_url(date: params[:date])
          return
        else
          flash[:danger] = "上長を選択してください"
          redirect_to attendances_edit_one_month_user_url(date:params[:date])
          return
        end
     end
   rescue ActiveRecord::RecordInvalid
     flash[:danger] = "無効なデータがあったのため、更新をキャンセルします"
     redirect_to attendances_edit_one_month_user_url(date: params[:date])
     return
   end
   
   #勤怠変更申請(上長)のお知らせモーダルの表示
   def edit_attendance_change_approval
     @attendances = Attendance.where(attendances_request_superiors: @user.name, attendance_approval_status: "申請中").order(:worked_on).group_by(&:user_id)
   end
   
   #勤怠変更申請のお知らせモーダル更新
 


#  def receive_change_attendance
#   @change_attendance_requests = Attendance.order(:worked_on).where(edit_attendance_boss: @user.id, edit_attendance_request_status: "申請中")
#  end
 
 
#  def update_change_attendance
#   ActiveRecord::Base.transaction do
#      change_attendance_params.each do |id, item|
#       change_attendance = Attendance.find(id)
#       if params[:user][:attendance][id][:change] == "true"
#          if change_attendance.started_at.nil? || change_attendance.finished_at.nil?
#           change_attendance.started_at = change_attendance.after_started_at
#           change_attendance.finished_at = change_attendance.after_finished_at
#          end
#       else
#          flash[:danger] = NO_CHECK_ERROR_MSG
#       end
#      end
#   end
#   flash[:success] = "勤怠変更の決済を更新しました。"
#   redirect_to user_url(date params[:date])
#  rescue ActiveRecord::RecordInvalid
#   flash[:danger] = INVALID_ERROR_MSG
#   redirect_to user_url(date: params[:date])
#  end
 #勤怠変更申請
 def update_attendance_change_approval
   a_count = 0
   attendance_approval_params.each do |id, item|
     attendance = Attendance.find(id)
     if item[:attendance_approval_check] == "1"
       unless item[:attendance_approval_status] == "申請中"|| item[:attendance_approval_status] == "なし"
         if item[:attendance_approval_status] == "承認"
           if attendance.before_started_at.blank? && attendance.before_finished_at.blank?
             attendance.before_started_at = attendance.after_started_at
             attendance.before_finished_at = attendance.after_finished_at
             item[:started_at] =attendance.after_started_at
             item[:finished_at] =attendance.after_finished_at
           end
          item[:started_at] =attendance.after_started_at
          item[:finished_at] =attendance.after_finished_at
         end
        a_count += 1
        attendance.update(item)
       end
       attendance.update(after_started_at: nil, after_finished_at: nil, note: nil, attendances_approval_status: nil,attendance_approval_check:false, next_day: nil ,change:false) if item[:attendances_approval_status] == "なし"
     end 
   end       
   if a_count > 0
     flash[:success] = "勤怠変更の承認に成功しました"
   else
     flash[:danger] = "勤怠変更の承認に失敗しました"
   end
   redirect_to user_url(@user)
 end
   
   
 #１ヶ月の勤怠申請
 def update_one_month_request
     one_month_request_params.each do |id, item|
       attendance = Attendance.find(id)
       if item[:one_month_request_boss].present?
         item[:one_month_request_status] = "申請中"
         if attendance.update(item)
           flash[:success] = "#{attendance.one_month_request_boss}へ１ヶ月の勤怠申請しました"
         else
           flash[:danger] = "1ヶ月の勤怠変更に失敗しました。"
         end
       else
         flash[:danger] = "上長を選択してください"
       end
     end
     redirect_to user_url(date: params[:date])
 end
 
 def edit_one_month_approval
     @attendances = Attendance.where(one_month_request_boss: @user.name, one_month_request_status: "申請中").order(:worked_on).group_by(&:user_id)
 end
 
 
 def update_one_month_approval
     one_month_approval_params.each do |id, item|
       attendance = Attendance.find(id)
       if item[:one_month_approval_check] == "1"
         if item[:one_month_approval_status] == "なし"
           item[:one_month_approval_status] = nil
           item[:one_month_approval_check] = nil
         end
         attendance.one_month_request_status = nil
         attendance.update(item)
         flash[:success] = "所属長承認申請の結果を送信しました。"
       else
         flash[:danger] = "承認確認のチェックを入れてください。"
       end
     end
     redirect_to user_url(@user)
 end


 def attendance_log
   if params["select_year(1i)"].present? && params["select_month(2i)"].present?
      @first_day = (params["select_year(1i)"] + "-" + params["select_month(2i)"] + "-01").to_date
      @attendances = @user.attendances.where(worked_on: @first_day..@first_day.end_of_month,attendance_approval_status: "承認").order(:worked_on)
   end
 end
 
 


 
 
  private
  
   def attendances_params
      params.require(:user).permit(attendances: [:note, :before_started_at, :before_finished_at, :after_started_at, :after_finished_at, :attendances_request_superiors, :change])[:attendances]
   end 
   
   #残業申請内容のストロングパラメーター
   def overtime_request_params
     params.require(:attendance).permit([:change_end_time,:reason_for_application,:overtime_next_day,:overtime_request_superior,:request_overtime_status])
   end
   
   def overtime_approval_params
     params.require(:user).permit(attendances: [:request_overtime_status,:overtime_check,:change])[:attendances]
   end

   # 勤怠情報修正承認・否認時のストロングパラメーター
   def change_attendance_params
     params.require(:user).permit(attendance: [:edit_attendance_request_status])[:attendances]
   end
   
   #勤怠変更承認のストロングパラメーター
   def attendance_approval_params
       params.require(:user).permit(attendances:[:before_started_at,:before_finished_at,:started_at,:finished_at,:after_started_at,:after_finished_at,:attendance_approval_status,:attendance_approval_check])[:attendances]
    
   end
   
   
   #１ヶ月の勤怠申請のストロングパラメーター

app/helpers/attendances_helper.rb
module AttendancesHelper
  require 'attendances_helper'
    def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
      return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    return false
    end 
    
    def working_times(after_finished_at,after_started_at,change)
        if change == true
          format("%.2f",24+((after_finished_at.hour - after_started_at.hour)))
        else
          format("%.2f",((after_finished_at.hour - after_started_at.hour)))
        end
     
    end
    
    #残業時間のフォーマット
    def overtime_culculation(change_end_time,designated_work_end_time,overtime_next_day )
      if overtime_next_day == "1"
        format("%.2f",24+(change_end_time.hour - designated_work_end_time.hour ) + ((change_end_time.min  - designated_work_end_time.min )/60.0))
      else 
        format("%.2f",(change_end_time.hour - designated_work_end_time.hour ) + ((change_end_time.min  - designated_work_end_time.min )/60.0))
      end
    end
    
    # def overtime_hours( change,constant)
    # format("%.2f",((change_end_time.hour*60)- (designated_work_end_time.hour*60))/60.0)
    # end
        
end

app/views/attendances/_edit_attendance_change_approval.html.erb
<% provide(:btn_text, "勤怠変更承認")%>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12">
            <%= form_with(model: @user, url: update_attendance_change_approval_user_attendance_path(@user), local: true, method: :patch) do |f| %>
              <% @attendances.each do |id, attendances|%>
              　<% user = User.find(id)%>
               <h1 class="modal-title"><%= "[#{user.name}からの勤怠申請]"%></h1>
               <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                <thead>
                  <tr>
                    <th rowspan="3">日付</th>
                    <th rowspan="3">曜日</th>
                    <th colspan="4">変更前</th>
                    <th colspan="4">変更後</th>
                    <th rowspan="3">備考</th>
                    <th rowspan="3">指示者確認㊞</th>
                    <th rowspan="3">変更</th>
                    <th rowspan="3">勤怠を確認する</th>
                  </tr>
                  <tr>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                  </tr>
                  <tr>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                  </tr>
                </thead>
                 <tbody>
                     <% attendances.each do |day|%>
                     <%= f.fields_for"attendances[]", day do |attendance|%>
                       <tr>
                         <td><%= l(day.worked_on, format: :short)%></td>
                         <td><%= $days_of_the_week[day.worked_on.wday] %></td>
                         <td><%=day.started_at.try(:strftime, "%H")%></td>
                         <td><%=day.started_at.try(:strftime, "%M")%></td>
                         <td><%=day.finished_at.try(:strftime, "%H")%></td>
                         <td><%=day.finished_at.try(:strftime, "%M")%></td>
                         <td><%=day.after_started_at.try(:strftime, "%H")%></td>
                         <td><%=day.after_started_at.try(:strftime, "%M")%></td>
                         <td><%=day.after_finished_at.try(:strftime, "%H")%></td>
                         <td><%=day.after_finished_at.try(:strftime, "%M")%></td>
                         <td><%=day.note%></td>
                         <td><%=attendance.select :attendance_approval_status, ['なし','申請中','承認','否認']%></td>
                         <td><%=attendance.check_box :attendance_approval_check%></td>
                         <td><%=link_to "確認", show_confirmation_user_path(user), class: "btn btn-primary"%></td>
                       </tr>
                     <% end %>
                   <% end %>
                 </tbody>
               </table>
               <div class="center">
                 <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block"%>
               </div>
              <% end %>
            <% end %>  
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/attendances/_edit_one_month_approval.html.erb
<% provide(:btn_text, '変更を返信する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
         
          <%= form_with(model: @user, url: update_one_month_approval_user_attendance_path(@user), local: true, method: :patch) do |f| %>
            <% @attendances.each do |id, attendances| %>
              <% user = User.find(id)%>
             
              <h1 class="modal-title"><%= "【#{user.name}の1ヶ月分勤怠申請】" %></h1>
               <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                <thead>
                  <tr>
                        <th>月</th>
                        <th>指示者確認㊞</th>
                        <th>変更</th>
                        <th>勤怠を確認する</th>
                  </tr>
                </thead>
                <tbody>
                  <% attendances.each do |day| %>              
                    <%= f.fields_for "attendances[]", day do |attendance| %>  
                    
                      <tr>
                        <td><%= day.worked_on.month %>月</td>
                        <td><%= attendance.select :one_month_approval_status, ['なし','申請中','承認','否認'] %></td>
                        <td><%= attendance.check_box :one_month_approval_check %></td>
                        <td><%= link_to "確認", show_confirmation_user_path(user, date: day.worked_on.beginning_of_month), class: "btn btn-primary" %></td>
                      
                      </tr>
                       
                    <% end %>
                  <% end %>
                </tbody>
              </table>
              <div class="center">
                <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_overtime_approval.html.erb
<% provide(:btn_text, "変更を送信")%>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">残業申請</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          <%= form_with(model: @user, url: update_overtime_approval_user_attendance_path(@user), local: true, method: :patch) do |f|%>
            <% @attendances.each do |id, attendances| %>
              <% user = User.find(id)%>
              <h1 class="modal-title"><%= "[#{user.name}からの残業申請]"%></h1>
                <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                  <thead>
                    <tr>
                      <th rowspan="2">日付</th>
                      <th rowspan="2">曜日</th>
                      <th colspan="2">終了予定時刻</th>
                      <th colspan="2">指定勤務終了時間</th>
                      <th rowspan="2">時間外時間</th>
                      <th rowspan="2">残業理由</th>
                      <th rowspan="2">指示者確認印</th>
                      <th rowspan="2">変更</th>
                      <th rowspan="2">勤怠を確認する</th>
                    </tr>
                    <tr>
                      <th>時</th>
                      <th>分</th>
                      <th>時</th>
                      <th>分</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% attendances.each do |day| %>
                      <%= f.fields_for"attendances[]", day do |attendance|%>
                        <tr>
                          <td><%= l(day.worked_on, format: :short)%></td>
                          <td><%= $days_of_the_week[day.worked_on.wday]  %></td>
                          <td><%=l(day.change_end_time,format: :hour) %></td>
                          <td><%=l(day.change_end_time,format: :minute) %></td>
                          <td><%=l(user.designated_work_end_time,format: :hour) %></td>
                          <td><%=l(user.designated_work_end_time,format: :minute) %></td>
                          <td><%= overtime_culculation(day.change_end_time, user.designated_work_end_time, day.overtime_next_day) if day.change_end_time.present?%></td>
                          <td><%= day.reason_for_application%></td>
                          <td><%= attendance.select :request_overtime_status, ["なし","申請中","承認","否認"] ,class: "form-control"%></td>
                          <td><%= attendance.check_box :overtime_check %></td>
                          <td><%= link_to "確認",show_confirmation_user_path(user, date: day.worked_on.beginning_of_month), class: "btn btn-sm btn-primary"%></td>
                        </tr>
                      <% end %>
                    <% end %>
                  </tbody>
                </table>
                <div class ="center">
                  <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block" %>
                </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_receive_change_attendance.html.erb
<% provide(:class_text, 'receive_change_attendance')%>
<% provide(:button_text, '変更を送信する')%>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button"class="close"data-dismiss="modal"aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: @user, url: attendances_update_change_attendance_user_path, local: true, method: :patch) do |f|%>
        <% @change_attendance_requests.each do |key, change_attendance_request| %>
          <table class="table table-bordered request-modal">
            
            <thead>
              <tr>
                <% @member = User.find(key)%>
                <h1 class = "modal-title"><%= User.find(key).name%>からの勤怠変更申請</h1>
                <th rowspan= "3">日付</th>
                <th rowspan ="3">曜日</th>
                <th colspan= "4">変更前</th>
                <th colspan= "4">変更後</th>
                <th rowspan ="3">備考</th>
                <th rowspan ="3">指示者確認印</th>
                <th rowspan ="3">変更</th>
                <th rowspan ="3">勤怠を確認する</th>
              </tr>
              
              <tr>
                <th colspan= "2">出社</th>
                <th colspan ="2">退社</th>
                <th colspan ="2">出社</th>
                <th colspan ="2">退社</th>
              </tr>
              
              <tr>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
              </tr>
            </thead>
            
            <tbody>
              <% change_attendance_request.each do |day| %>
                <%= f.fields_for "attendances[]", day do |attendance| %>
                <tr>
                  <td><%= l(day.worked_on, format: :short) %></td>
                  <td><%= $day_of_the_week[days.worked_on.wday]%></td> 
                  <td><%= day.started_at.hour if day.started_at.present? %></td>
                  <td><%= day.started_at.minute if day.started_at.present? %></td>
                  <td><%= day.finished_at.hour if day.finished_at.present?%></td>
                  <td><%= day.finished_at.minite if day.finished_at.present? %></td>
                  <td><%= day.after_started_at.hour if day.after_started_at.present? %></td>
                  <td><%= day.after_started_at.minite if day.after_started_at.present?%></td>
                  <td><%= day.after_finished_at.hour if day.after_finished_at.present?%></td>
                  <td><%= day.after_finished_at.minite if day.after_finished_at.present?%></td>
                  <td><%= day.note %></td>
                  <td><%= attendance.select :edit_attendance_request_status, Attendance.edit_attendance_request_statuses.keys.to_a,{}, class: "form-control" %></td>
                  <td><%= attendance.check_box :change, {class: "check_box"}, true, false %></td>
                  <td><%= link_to "確認",user_path(id: @member, date: day.worked_on.beginning_of_month), class: "btn btn-primary btn-#{yield(:class_text)}"%></td>
                </tr>
              <% end %>
            <% end %>
            </tbody>
          </table>
        <% end %>
        
      <table>
        <div class = "footer-button">
          <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}"%>
            <button type ="button" class="btn btn-primary btn-<%= yield(:class_text)%>" data-dismiss = "modal">
              戻る
            </button>
        </div>
      </table>
    <% end %>
  </div>
</div>

app/views/attendances/edit_attendance_change_approval.js.erb
$("#edit-attendance-change-approval").html("<%= escape_javascript(render 'edit_attendance_change_approval') %>");
$("#edit-attendance-change-approval").modal("show");

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f|%>
<div>
  <h1>勤怠編集画面</h1>
    <table class = "table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出勤</th>
          <th>退勤</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th>備考</th>
          <th>指示者確認印</th>
        </tr>
      </thead>    
    
      <tbody>
        <% @attendances.each do |day|%>
          <%= f.fields_for"attendances[]", day do |attendance|%>
              <tr>
                <td><%= l(day.worked_on, format: :short)%></td>
                <td><%= $days_of_the_week[day.worked_on.wday] %></td>
                <% if (Date.current < day.worked_on )%>
                  <td><%= attendance.time_field :after_started_at, readonly: true, class: "form-control"%></td>
                  <td><%= attendance.time_field :after_finished_at, readonly: true, class: "form-control"%></td>
                <% else %>
                  <td>
                   <% if day.started_at.present?%>
                    <% day.after_started_at = day.started_at %>
                    <%= attendance.time_field :after_started_at, class: "form-control"%>
                   <% else %>
                    <%= attendance.time_field :after_started_at, class: "form-control"%>
                   <% end %>
                  </td>
                  <td>
                   <% if day.finished_at.present?%>
                     <% day.after_finished_at = day.finished_at %>
                     <%= attendance.time_field :after_finished_at, class: "form-control"%>
                   <% else day.finished_at.present? && day.change_end_time.present? %>
                    <% day.after_finished_at = day.change_end_time%>
                    <%= attendance.time_field :after_finished_at, class: "form-control"%>
                   <% end %>
                  </td>
                  <% end %>
                <td><%= attendance.check_box :change %></td>
                <td><%= overtime_culculation(day.change_end_time, @user.designated_work_end_time, day.overtime_next_day) if day.change_end_time.present?%></td>
                <td><%= attendance.text_field :note, placeholder: "変更理由を入力してください", class: "form-control" if Date.current >= day.worked_on %></td>
                <td><%= attendance.collection_select :attendances_request_superiors, @superiors, :name, :name, {include_blank: "選択してください", selected: "選択してください"},
                {class: "form-control"} if Date.current >= day.worked_on%></td>
              </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
    <div class= "center">
      <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
      <%= link_to "戻る", user_path(date: @first_day), class: "btn btn-lg btn-primary" %>
    </div>
<% end %>

app/views/attendances/edit_overtime_approval.js.erb
$("#edit-overtime-approval").html("<%= escape_javascript(render 'edit_overtime_approval') %>");
$("#edit-overtime-approval").modal("show");

app/views/attendances/edit_overtime_request.js.erb
$("#edit-overtime-request").html("<%= escape_javascript(render 'edit_overtime_request') %>");
$("#edit-overtime-request").modal("show");

app/views/attendances/receive_change_attendance.js.erb
$("#receive-change-attendance").html("<%= escape_javascript(render 'receive_change_attendance')%>");
$("#receive-change-attendance").modal("show");