config/routes.rb
Rails.application.routes.draw do
  root 'attendance_page#top'
  
  get '/signup', to:'users#new'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  
  
  resources :bases, only:[:new, :index, :create, :edit, :update, :destroy]

 
 resources :users do
  member do
   get 'edit_basic_info'
   patch 'update_basic_info'
   get 'form_edit'
   get 'info_correction'
   get 'attendances/edit_one_month'
   patch 'attendances/update_one_month'
   #勤怠を確認する
   get 'show_confirmation'
   #１ヶ月の勤怠申請
   patch 'attendances/update_one_month_request'
   get 'worker'
   
  end 
  collection {post :import}
  
  resources :attendances, only: :update do
    member do
      
      #残業申請
      get 'edit_overtime_request'
      patch 'update_overtime_request'
      
      #残業申請承認
      get 'edit_overtime_approval'
      patch 'update_overtime_approval'
      
      #勤怠承認
      get 'edit_attendance_change_approval'
      patch 'update_attendance_change_approval'  
      
      #1ヶ月の勤怠承認
      get 'edit_one_month_approval'
      patch 'update_one_month_approval'
      
      get 'attendance_log'
    end 
  end
 end
end
  

app/views/layouts/_header.html.erb
 <header class = "navbar navbar-fixed-top navbar-inverse" >
      <div class = "container">
        <%= link_to "勤怠システム", root_path, id: "logo"%>
        <nav>
          <ul class = "nav navbar-nav navbar-right">
            <li><%= link_to "TOP", root_path%></li>
         
            <% if logged_in? %>
               <% if current_user.admin? %>
                <li><%= link_to "ユーザー一覧", users_path%></li>
                <li><%= link_to "出社社員一覧", worker_user_path(current_user)%></li>
                <li><%= link_to "拠点情報修正", bases_path%></li>
                <li><%= link_to "基本情報の修正",info_correction_user_path(current_user)%></li>
               <% end %>
               <li class = "dropdown">
                 <a href = "#" class= "dropdown-toggle" data-toggle="dropdown">Acount<b class ="caret"></b></a>
                 <ul class = "dropdown-menu">
                   <% unless current_user.admin? %>
                     <li><%= link_to "勤怠", current_user %></li>
                   <% end %>
                     <li><%= link_to "設定",form_edit_user_path(current_user)%></li>
                     <li class = "divider"></li>
                     <li><%= link_to "LOG OUT",logout_path, method: :delete %></li>
                 </ul>
               </li>
            <% else %>
                  <li><%= link_to "LOGIN", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
  <div id="main-message">
    <div class="container">
      <% flash.each do |message_type,msg| %>
       <div class = "alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
  </div>
</html>